# cert-manager setup for Dental Management Dashboard
# This file sets up automatic SSL certificate management with Let's Encrypt

---
# ClusterIssuer for Let's Encrypt Production
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Your email address for Let's Encrypt notifications
    email: info@bytheapp.com  # CHANGE THIS TO YOUR EMAIL
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # HTTP-01 challenge solver
    solvers:
    - http01:
        ingress:
          class: nginx

---
# ClusterIssuer for Let's Encrypt Staging (for testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server (for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: info@bytheapp.com  # CHANGE THIS TO YOUR EMAIL
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx

---
# Certificate resource (optional - cert-manager can create this automatically)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dental-dashboard-tls
spec:
  secretName: dental-dashboard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - dental-dashboard.bytheapp.com  # CHANGE THIS TO YOUR DOMAIN
