apiVersion: v1
kind: ConfigMap
metadata:
  name: dental-management-config
  labels:
    app: dental-management-dashboard
data:
  # API Configuration
  REACT_APP_API_BASE_URL: "https://api-demo.bytheapp.com"
  REACT_APP_APP_NAME: "Dental Management Dashboard"
  REACT_APP_APP_VERSION: "1.0.0"
  REACT_APP_ENVIRONMENT: "production"
  REACT_APP_API_TIMEOUT: "15000"
  REACT_APP_API_RETRY_ATTEMPTS: "3"
  REACT_APP_DEBUG: "false"
  REACT_APP_LOG_LEVEL: "error"
  REACT_APP_ENABLE_ANALYTICS: "true"
  REACT_APP_ENABLE_ERROR_REPORTING: "true"
  REACT_APP_DOMAIN: "dental-dashboard.yourdomain.com"
  REACT_APP_APP_URL: "https://dental-dashboard.yourdomain.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dental-management-dashboard
  labels:
    app: dental-management-dashboard
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dental-management-dashboard
  template:
    metadata:
      labels:
        app: dental-management-dashboard
        version: v1.0.0
    spec:
      containers:
      - name: dental-dashboard
        image: dental-management-dashboard:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        envFrom:
        - configMapRef:
            name: dental-management-config
        env:
        - name: NODE_ENV
          value: "production"
      imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dental-management-service
  labels:
    app: dental-management-dashboard
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: dental-management-dashboard
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dental-management-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - dental-dashboard.yourdomain.com
    secretName: dental-dashboard-tls
  rules:
  - host: dental-dashboard.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dental-management-service
            port:
              number: 80
