apiVersion: apps/v1
kind: Deployment
metadata:
  name: dental-management-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dental-management-app
  template:
    metadata:
      labels:
        app: dental-management-app
    spec:
      containers:
      - name: dental-management-app
        image: #{repository-image}#
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          value: "https://api-demo.bytheapp.com"
        - name: VITE_APP_NAME
          value: "Dental Management Dashboard"
        - name: VITE_APP_VERSION
          value: "#{Build.BuildNumber}#"
        - name: VITE_ENVIRONMENT
          value: "#{env-name}#"
        - name: VITE_DOMAIN
          value: "#{host-url}#"
        - name: VITE_APP_URL
          value: "https://#{host-url}#"
        - name: SKIP_PREFLIGHT_CHECK
          value: "#{SKIP_PREFLIGHT_CHECK}#"
      imagePullSecrets:
        - name: #{acr-secret-name}#
---
apiVersion: v1
kind: Service
metadata:
  name: dental-management-app-service
spec:
  selector:
    app: dental-management-app
  ports:
  - port: 80
    targetPort: 80
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dental-management-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = '' ) {
        rewrite ^ https://www.$request_uri permanent;
      }
  name: dental-management-app-ingress
  namespace: #{env-namespace}#
spec:
  tls:
  - hosts:
    - #{host-url}#
    secretName: dental-dashboard-ingress-tls
  rules:
    - host: #{host-url}#
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dental-management-app-service
              port:
                number: 80
